### PR TITLE
Convert to ARC.

### PR DESCRIPTION
**Pull request by jwilling**

### CODE REVIEW

**Comment by psineur** [comment]
Why closing? I like having original AMC in noARC, but someone maybe interested using ARC version.
ReOpened.

**Comment by jwilling** [comment]
Heh, I thought this project was dead so I was cleaning up my PRs a bit since this has been open for quite some time now.

**Comment by psineur** [comment]
Oops, looks like i can not reopen this.

**Comment by psineur** [comment]
Well it's not dead, it still works and just needs no modification.

**Comment by jwilling** [comment]
I believe that's because I deleted my fork a long time ago. :disappointed:

**Comment by jwilling** [comment]
If you want to, feel free to cherry-pick whatever you want, maybe just throw it in a branch or something if you want to have ARC compatibility.

**Comment by psineur** [comment]
Will do, thanks

**Pull request closed without merging**
